### ISSUE TITLE
Error importing moment-timezone with ember-auto-import 2.6.2

### ISSUE THREAD

**Issue by dwickern** [adopted-ember-addons/ember-moment#396]
After upgrading ember-auto-import from 2.6.1 to 2.6.2, the app has a runtime failure importing moment-timezone:
```
caught (in promise) Error: Could not find module `moment-timezone` imported from `ember-moment/services/moment.js`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at Module.findDeps (loader.js:168:1)
    at findModule (loader.js:262:1)
    at Module.findDeps (loader.js:168:1)
    at findModule (loader.js:262:1)
    at requireModule (loader.js:24:1)
    at ModuleRegistry.get (index.js:30:1)
    at Class._extractDefaultExport (index.js:464:1)
    at Class.resolveOther (index.js:126:1)
m
```

The app does not have a dependency on moment-timezone.

**Comment by NullVoxPopuli** [comment]
Are you using yarn or npm? Is it possible that the devDeps of ember-moment got installed, or some other dependency has brought in moment-timezone, and dependency hoisting my the package manager has caused an incorrect node_modules, making ember-moment think moment-timezone is there?

```
yarn why moment-timezone
npm ls moment-timezone 
```

Other than that, a reproduction repo would be most helpful
